# Dockerfile
FROM centos:7.6.1810

RUN yum --assumeyes update && yum --assumeyes install \
    gcc \
    gcc-c++\
    libxml2 \
    libxml2-devel \
    git \
    openssl \
    openssl-devel \
    ncurses-devel \
    bison \
    flex \
    redhat-lsb \
    rpm-build \
    libedit \
    libedit-devel \
    cmake
WORKDIR /work
