# Dockerfile
FROM fedora:27

RUN dnf install -y \
    gcc \
    gcc-c++\
    libxml2 \
    libxml2-devel \
    git \
    openssl \
    openssl-devel \
    ncurses-devel \
    libedit \
	libedit-devel \
    bison \
    flex \
    redhat-lsb \
    rpmdevtools \
    cmake
WORKDIR /work
COPY . /work/titan.core
WORKDIR /work/titan.core/build
RUN cmake .. && make package
CMD ["/bin/bash"]
